//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.WinFormsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizApp.WinFormsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password first..
        /// </summary>
        internal static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this quiz?.
        /// </summary>
        internal static string delete_quiz {
            get {
                return ResourceManager.GetString("delete_quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        internal static string delete_user {
            get {
                return ResourceManager.GetString("delete_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard this question?.
        /// </summary>
        internal static string discard_question {
            get {
                return ResourceManager.GetString("discard_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard the current quiz?.
        /// </summary>
        internal static string discard_quiz {
            get {
                return ResourceManager.GetString("discard_quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard the current user?.
        /// </summary>
        internal static string discard_user {
            get {
                return ResourceManager.GetString("discard_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tracecollege.edu.ph.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Saving the Quiz..
        /// </summary>
        internal static string failed_save {
            get {
                return ResourceManager.GetString("failed_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files (*.csv)|*.csv.
        /// </summary>
        internal static string files_csv {
            get {
                return ResourceManager.GetString("files_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz, JSON, Text files (*.quiz, *.json, *.txt)|*.quiz;*.json;*.txt.
        /// </summary>
        internal static string files_supported {
            get {
                return ResourceManager.GetString("files_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz files (*.quiz)|*.quiz|JSON files (*.json)|*.json|Text files (*.txt)|*.txt.
        /// </summary>
        internal static string files_supported_separate {
            get {
                return ResourceManager.GetString("files_supported_separate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load quiz from file..
        /// </summary>
        internal static string load_failed_quiz {
            get {
                return ResourceManager.GetString("load_failed_quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be an answer first..
        /// </summary>
        internal static string no_answer {
            get {
                return ResourceManager.GetString("no_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be an answer to the boxes above..
        /// </summary>
        internal static string no_answer_above {
            get {
                return ResourceManager.GetString("no_answer_above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No syntax errors found..
        /// </summary>
        internal static string no_syntax_error {
            get {
                return ResourceManager.GetString("no_syntax_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully updated..
        /// </summary>
        internal static string password_updated_success {
            get {
                return ResourceManager.GetString("password_updated_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save the quiz?.
        /// </summary>
        internal static string save_confirmation {
            get {
                return ResourceManager.GetString("save_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question saved successfully..
        /// </summary>
        internal static string save_question_success {
            get {
                return ResourceManager.GetString("save_question_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz saved successfully..
        /// </summary>
        internal static string save_success {
            get {
                return ResourceManager.GetString("save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save the user?.
        /// </summary>
        internal static string save_user_confirmation {
            get {
                return ResourceManager.GetString("save_user_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an answer..
        /// </summary>
        internal static string select_answer {
            get {
                return ResourceManager.GetString("select_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Registered? Login here.
        /// </summary>
        internal static string switch_entry_form_login {
            get {
                return ResourceManager.GetString("switch_entry_form_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet? Register here.
        /// </summary>
        internal static string switch_entry_form_register {
            get {
                return ResourceManager.GetString("switch_entry_form_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Quiz.
        /// </summary>
        internal static string test_quiz {
            get {
                return ResourceManager.GetString("test_quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test score: {0}.
        /// </summary>
        internal static string test_score {
            get {
                return ResourceManager.GetString("test_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trace_logo {
            get {
                object obj = ResourceManager.GetObject("trace_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon trace_logo_ico {
            get {
                object obj = ResourceManager.GetObject("trace_logo_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        internal static string welcome_user {
            get {
                return ResourceManager.GetString("welcome_user", resourceCulture);
            }
        }
    }
}
